// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "courier-app/dto"
	entity "courier-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// ShippingUsecase is an autogenerated mock type for the ShippingUsecase type
type ShippingUsecase struct {
	mock.Mock
}

// CreateShipping provides a mock function with given fields: userId, req
func (_m *ShippingUsecase) CreateShipping(userId uint, req *dto.ShippingCreateRequest) (*entity.Shipping, error) {
	ret := _m.Called(userId, req)

	var r0 *entity.Shipping
	if rf, ok := ret.Get(0).(func(uint, *dto.ShippingCreateRequest) *entity.Shipping); ok {
		r0 = rf(userId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Shipping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *dto.ShippingCreateRequest) error); ok {
		r1 = rf(userId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: paging
func (_m *ShippingUsecase) GetAll(paging *dto.ShippingTableRequest) (*[]entity.Shipping, *dto.Pagination, error) {
	ret := _m.Called(paging)

	var r0 *[]entity.Shipping
	if rf, ok := ret.Get(0).(func(*dto.ShippingTableRequest) *[]entity.Shipping); ok {
		r0 = rf(paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Shipping)
		}
	}

	var r1 *dto.Pagination
	if rf, ok := ret.Get(1).(func(*dto.ShippingTableRequest) *dto.Pagination); ok {
		r1 = rf(paging)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.Pagination)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*dto.ShippingTableRequest) error); ok {
		r2 = rf(paging)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetById provides a mock function with given fields: id
func (_m *ShippingUsecase) GetById(id uint) (*entity.Shipping, error) {
	ret := _m.Called(id)

	var r0 *entity.Shipping
	if rf, ok := ret.Get(0).(func(uint) *entity.Shipping); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Shipping)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserId provides a mock function with given fields: userId, paging
func (_m *ShippingUsecase) GetByUserId(userId uint, paging *dto.ShippingTableRequest) (*[]entity.Shipping, *dto.Pagination, error) {
	ret := _m.Called(userId, paging)

	var r0 *[]entity.Shipping
	if rf, ok := ret.Get(0).(func(uint, *dto.ShippingTableRequest) *[]entity.Shipping); ok {
		r0 = rf(userId, paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Shipping)
		}
	}

	var r1 *dto.Pagination
	if rf, ok := ret.Get(1).(func(uint, *dto.ShippingTableRequest) *dto.Pagination); ok {
		r1 = rf(userId, paging)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*dto.Pagination)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(uint, *dto.ShippingTableRequest) error); ok {
		r2 = rf(userId, paging)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetShippingStatuses provides a mock function with given fields:
func (_m *ShippingUsecase) GetShippingStatuses() (*[]entity.ShippingStatus, error) {
	ret := _m.Called()

	var r0 *[]entity.ShippingStatus
	if rf, ok := ret.Get(0).(func() *[]entity.ShippingStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.ShippingStatus)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Review provides a mock function with given fields: userId, req
func (_m *ShippingUsecase) Review(userId uint, req *dto.ShippingReviewRequest) error {
	ret := _m.Called(userId, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, *dto.ShippingReviewRequest) error); ok {
		r0 = rf(userId, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: shippingId, statusId
func (_m *ShippingUsecase) UpdateStatus(shippingId uint, statusId uint) error {
	ret := _m.Called(shippingId, statusId)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(shippingId, statusId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewShippingUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewShippingUsecase creates a new instance of ShippingUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewShippingUsecase(t mockConstructorTestingTNewShippingUsecase) *ShippingUsecase {
	mock := &ShippingUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
