// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "courier-app/dto"
	entity "courier-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionUsecase is an autogenerated mock type for the TransactionUsecase type
type TransactionUsecase struct {
	mock.Mock
}

// GetTotalSpendingByUser provides a mock function with given fields: userId
func (_m *TransactionUsecase) GetTotalSpendingByUser(userId uint) (float64, error) {
	ret := _m.Called(userId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(uint) float64); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TopUp provides a mock function with given fields: userId, req
func (_m *TransactionUsecase) TopUp(userId uint, req *dto.TopUpRequestBody) (*entity.Transaction, error) {
	ret := _m.Called(userId, req)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(uint, *dto.TopUpRequestBody) *entity.Transaction); ok {
		r0 = rf(userId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, *dto.TopUpRequestBody) error); ok {
		r1 = rf(userId, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionUsecase creates a new instance of TransactionUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionUsecase(t mockConstructorTestingTNewTransactionUsecase) *TransactionUsecase {
	mock := &TransactionUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
