// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "courier-app/dto"
	entity "courier-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// AddressRepository is an autogenerated mock type for the AddressRepository type
type AddressRepository struct {
	mock.Mock
}

// CreateAddress provides a mock function with given fields: address
func (_m *AddressRepository) CreateAddress(address *entity.Address) (*entity.Address, error) {
	ret := _m.Called(address)

	var r0 *entity.Address
	if rf, ok := ret.Get(0).(func(*entity.Address) *entity.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Address) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAddress provides a mock function with given fields: address
func (_m *AddressRepository) DeleteAddress(address *entity.Address) (*entity.Address, error) {
	ret := _m.Called(address)

	var r0 *entity.Address
	if rf, ok := ret.Get(0).(func(*entity.Address) *entity.Address); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Address) error); ok {
		r1 = rf(address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: paging
func (_m *AddressRepository) GetAll(paging *dto.AddressPaginationRequest) (*[]entity.Address, error) {
	ret := _m.Called(paging)

	var r0 *[]entity.Address
	if rf, ok := ret.Get(0).(func(*dto.AddressPaginationRequest) *[]entity.Address); ok {
		r0 = rf(paging)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.AddressPaginationRequest) error); ok {
		r1 = rf(paging)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *AddressRepository) GetById(id uint) (*entity.Address, error) {
	ret := _m.Called(id)

	var r0 *entity.Address
	if rf, ok := ret.Get(0).(func(uint) *entity.Address); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Address)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCountAll provides a mock function with given fields: paging
func (_m *AddressRepository) GetCountAll(paging *dto.AddressPaginationRequest) (int64, error) {
	ret := _m.Called(paging)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*dto.AddressPaginationRequest) int64); ok {
		r0 = rf(paging)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*dto.AddressPaginationRequest) error); ok {
		r1 = rf(paging)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAddress provides a mock function with given fields: address
func (_m *AddressRepository) UpdateAddress(address *entity.Address) error {
	ret := _m.Called(address)

	var r0 error
	if rf, ok := ret.Get(0).(func(*entity.Address) error); ok {
		r0 = rf(address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAddressRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAddressRepository creates a new instance of AddressRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAddressRepository(t mockConstructorTestingTNewAddressRepository) *AddressRepository {
	mock := &AddressRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
