// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "courier-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: txreq
func (_m *TransactionRepository) CreateTransaction(txreq *entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(txreq)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(*entity.Transaction) *entity.Transaction); ok {
		r0 = rf(txreq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Transaction) error); ok {
		r1 = rf(txreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalSpendingByUser provides a mock function with given fields: userId
func (_m *TransactionRepository) GetTotalSpendingByUser(userId uint) (float64, error) {
	ret := _m.Called(userId)

	var r0 float64
	if rf, ok := ret.Get(0).(func(uint) float64); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionRepository(t mockConstructorTestingTNewTransactionRepository) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
