// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	dto "courier-app/dto"
	entity "courier-app/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// ChangeGachaQuota provides a mock function with given fields: userId, amount
func (_m *UserRepository) ChangeGachaQuota(userId uint, amount int) error {
	ret := _m.Called(userId, amount)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, int) error); ok {
		r0 = rf(userId, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByEmail provides a mock function with given fields: email
func (_m *UserRepository) GetByEmail(email string) (*entity.User, error) {
	ret := _m.Called(email)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *UserRepository) GetById(id uint) (*entity.User, error) {
	ret := _m.Called(id)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(uint) *entity.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByReferral provides a mock function with given fields: referral
func (_m *UserRepository) GetByReferral(referral string) (*entity.User, error) {
	ret := _m.Called(referral)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(string) *entity.User); ok {
		r0 = rf(referral)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(referral)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailsById provides a mock function with given fields: id
func (_m *UserRepository) GetDetailsById(id uint) (*entity.UserDetail, error) {
	ret := _m.Called(id)

	var r0 *entity.UserDetail
	if rf, ok := ret.Get(0).(func(uint) *entity.UserDetail); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserBalance provides a mock function with given fields: id
func (_m *UserRepository) GetUserBalance(id uint) (*dto.UserBalanceResponse, error) {
	ret := _m.Called(id)

	var r0 *dto.UserBalanceResponse
	if rf, ok := ret.Get(0).(func(uint) *dto.UserBalanceResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserBalanceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserGachaQuota provides a mock function with given fields: id
func (_m *UserRepository) GetUserGachaQuota(id uint) (*dto.UserGachaQuotaResponse, error) {
	ret := _m.Called(id)

	var r0 *dto.UserGachaQuotaResponse
	if rf, ok := ret.Get(0).(func(uint) *dto.UserGachaQuotaResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UserGachaQuotaResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: _a0
func (_m *UserRepository) Register(_a0 *entity.User) (*entity.User, error) {
	ret := _m.Called(_a0)

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(*entity.User) *entity.User); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RewardReferralClaimer provides a mock function with given fields: txreq
func (_m *UserRepository) RewardReferralClaimer(txreq *entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(txreq)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(*entity.Transaction) *entity.Transaction); ok {
		r0 = rf(txreq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entity.Transaction) error); ok {
		r1 = rf(txreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RewardReferralOwner provides a mock function with given fields: claimerId, referralCode, txreq
func (_m *UserRepository) RewardReferralOwner(claimerId uint, referralCode string, txreq *entity.Transaction) (*entity.Transaction, error) {
	ret := _m.Called(claimerId, referralCode, txreq)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(uint, string, *entity.Transaction) *entity.Transaction); ok {
		r0 = rf(claimerId, referralCode, txreq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, *entity.Transaction) error); ok {
		r1 = rf(claimerId, referralCode, txreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: _a0
func (_m *UserRepository) UpdateProfile(_a0 *dto.UserProfile) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.UserProfile) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepository(t mockConstructorTestingTNewUserRepository) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
